using System;
using System.IO;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media.Imaging;
using System.Windows.Input;

namespace SoftcurseMediaLabAI.Views
{
    public partial class GenerativeFillPage : UserControl
    {
        private string _imagePath;
        private byte[]? _maskBytes;
        private CancellationTokenSource? _cts;

        public string? ResultImagePath { get; private set; }

        public GenerativeFillPage(string? imagePath = null, byte[]? maskBytes = null)
        {
            InitializeComponent();
            _imagePath = imagePath ?? string.Empty;
            _maskBytes = maskBytes;
            ApiEndpointTextBox.Text = AppSettings.ApiEndpoint;
            UpdateSourceContext();
        }

        /// <summary>
        /// Allows MainWindow or ImageEditorPage to pass the current image to this page.
        /// </summary>
        public void SetImage(string imagePath, byte[]? maskBytes = null)
        {
            _imagePath = imagePath;
            _maskBytes = maskBytes;
            ApiEndpointTextBox.Text = AppSettings.ApiEndpoint;
            UpdateSourceContext();
        }

        private void UpdateSourceContext()
        {
            bool hasImage = !string.IsNullOrWhiteSpace(_imagePath) && File.Exists(_imagePath);
            GenerateButton.IsEnabled = hasImage;
            SourceModeText.Text = !hasImage
                ? "Load an image in Image Editor first; sending is disabled until a source exists."
                : _maskBytes is { Length: > 0 }
                    ? "MASKED INPAINT: only the supplied mask region will be regenerated by the API."
                    : "WHOLE-IMAGE IMG2IMG: no mask was supplied, so the API may transform the entire image.";
        }

        private void Cancel_Click(object sender, RoutedEventArgs e)
        {
            _cts?.Cancel();
            CancelButton.IsEnabled = false;
        }

        private async void Generate_Click(object sender, RoutedEventArgs e)
        {
            if (string.IsNullOrEmpty(_imagePath))
            {
                DarkMessageBox.Show("Please load an image into Image Editor first, then open Generative Image API.\n\nThis optional tool sends the current image to the compatible API configured in Settings.", "Missing Image", MessageBoxButton.OK, MessageBoxImage.Warning);
                return;
            }
            if (string.IsNullOrWhiteSpace(PromptTextBox.Text))
            {
                DarkMessageBox.Show("Describe what you want to generate first.", "Prompt Required", MessageBoxButton.OK, MessageBoxImage.Information);
                PromptTextBox.Focus();
                return;
            }

            GenerateButton.IsEnabled = false;
            CancelButton.IsEnabled = true;
            _cts = new CancellationTokenSource();

            string prompt = PromptTextBox.Text;
            string negativePrompt = NegativePromptTextBox.Text;
            string apiUrl = AppSettings.ApiEndpoint;

            // F-04: validate URL before making any network request
            if (!AppSettings.IsApiEndpointSafe(apiUrl, out string genUrlError))
            {
                DarkMessageBox.Show($"Generative Fill API endpoint is invalid:\n{genUrlError}\n\nPlease update it in Settings.", "Invalid API Endpoint", MessageBoxButton.OK, MessageBoxImage.Warning);
                GenerateButton.IsEnabled = true;
                CancelButton.IsEnabled = false;
                return;
            }

            try
            {
                if (GenerativeApiClient.IsRemoteEndpoint(apiUrl))
                {
                    MessageBoxResult choice = DarkMessageBox.Show(
                        "This API is remote. The current image will be uploaded to the configured server. Continue only if you trust it.",
                        "Remote API Privacy", MessageBoxButton.YesNo, MessageBoxImage.Warning);
                    if (choice != MessageBoxResult.Yes) return;
                }

                string base64Image = Convert.ToBase64String(File.ReadAllBytes(_imagePath));
                string? base64Mask = _maskBytes != null ? Convert.ToBase64String(_maskBytes) : null;

                var payload = new
                {
                    prompt = prompt,
                    negative_prompt = negativePrompt,
                    init_images = new[] { base64Image },
                    mask = base64Mask,
                    inpainting_fill = 1, // original
                    inpaint_full_res = true,
                    inpaint_full_res_padding = 32,
                    inpainting_mask_invert = 0,
                    steps = 20,
                    cfg_scale = 7.0,
                    width = 512,
                    height = 512,
                    restore_faces = false,
                    denoising_strength = 0.75
                };

                using JsonDocument doc = await GenerativeApiClient.PostJsonAsync(
                    apiUrl, "sdapi/v1/img2img", payload, _cts.Token);
                if (doc.RootElement.TryGetProperty("images", out JsonElement imagesElement) && imagesElement.GetArrayLength() > 0)
                {
                    string returningBase64 = imagesElement[0].GetString()
                        ?? throw new GenerativeApiException("API returned an empty image payload.");
                    byte[] returningBytes = Convert.FromBase64String(returningBase64);

                    string tempFile = TempFileManager.CreateTempPath("genfill", ".png");
                    File.WriteAllBytes(tempFile, returningBytes);
                    ImageFileValidator.Validate(tempFile);

                    ResultImagePath = tempFile;
                    DarkMessageBox.Show("Generation complete. The result is now open in Image Editor.", "Success", MessageBoxButton.OK, MessageBoxImage.Information);

                    var mainWindow = Application.Current.MainWindow as MainWindow;
                    mainWindow?.OpenImageInEditor(tempFile);
                    return;
                }
                throw new GenerativeApiException("API returned no generated images.");
            }
            catch (OperationCanceledException)
            {
                // Cancelled by user.
            }
            catch (Exception ex)
            {
                DarkMessageBox.Show(ex.Message, "Generation Failed", MessageBoxButton.OK, MessageBoxImage.Warning);
            }
            finally
            {
                GenerateButton.IsEnabled = true;
                CancelButton.IsEnabled = false;
                _cts?.Dispose();
                _cts = null;
            }
        }

        private void UserControl_PreviewKeyDown(object sender, KeyEventArgs e)
        {
            if (e.Key == Key.Enter && Keyboard.Modifiers == ModifierKeys.Control && GenerateButton.IsEnabled)
            {
                Generate_Click(GenerateButton, new RoutedEventArgs());
                e.Handled = true;
            }
            else if (e.Key == Key.Escape && CancelButton.IsEnabled)
            {
                Cancel_Click(CancelButton, new RoutedEventArgs());
                e.Handled = true;
            }
        }

    }
}
